language: kotlin

jdk:
  - oraclejdk8

os:
  - linux

before_script:
  - wget https://services.gradle.org/distributions/gradle-4.5.1-bin.zip
  - unzip gradle-4.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH

script: 
  - ./gradlew check